apiVersion: v1
kind: Service
metadata:
  name: pictune-music
  namespace: pictune
  labels:
    app: pictune-music
spec:
  type: ClusterIP
  selector:
    app: pictune-music
  ports:
    - name: http
      port: 8002
      targetPort: music-http
